# Generated by Django 5.2.5 on 2026-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TERCERO', 'Pago por Tercero'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagado_por',
            field=models.CharField(blank=True, help_text='Nombre del tercero si aplica', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Comprobante / Referencia'),
        ),
    ]
