# Generated by Django 5.2.5 on 2026-03-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_pago_metodo_pago_pago_notas_pago_pagado_por_and_more'),
        ('clientes', '0002_alter_cliente_options_and_more'),
        ('ventas', '0004_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha', '-fecha_registro'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia__isnull', False)), fields=('cliente', 'fecha', 'referencia'), name='unique_pago_por_cliente_fecha_referencia'),
        ),
    ]
