# Generated by Django 5.2.5 on 2026-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_alter_pago_options_pago_cliente_and_more'),
        ('clientes', '0002_alter_cliente_options_and_more'),
        ('ventas', '0004_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_pago_por_cliente_fecha_referencia',
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia__isnull', False)), fields=('cliente', 'fecha', 'referencia'), name='unique_pago_cliente_fecha_referencia'),
        ),
    ]
