# Generated by Django 5.2.5 on 2026-03-03 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('FINANCIERO', 'Evento Financiero (Pago/Saldo)'), ('LOGISTICO', 'Evento Logístico (Carga/Entrega)'), ('SISTEMA', 'Cambio de Configuración / Precios'), ('ALERTA', 'Alerta de Seguridad o Descuadre')], default='FINANCIERO', max_length=20)),
                ('descripcion', models.TextField()),
                ('referencia_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos técnicos del evento (ej: payload antes/después)')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
