# Generated by Django 5.2.5 on 2025-09-04 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('embarque', models.CharField(max_length=50)),
                ('dia_embarque', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('factura', models.CharField(max_length=50, unique=True)),
                ('conductor', models.CharField(blank=True, max_length=100, null=True)),
                ('flete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_con_flete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('DEBE', 'Debe'), ('PAGADA', 'Pagada'), ('PARCIAL', 'Pago Parcial')], default='DEBE', max_length=10)),
                ('mes', models.CharField(max_length=20)),
                ('dias', models.PositiveIntegerField(default=0)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidad_medida', models.CharField(default='UND', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
    ]
