# Generated by Django 5.2.5 on 2026-03-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='numero',
            new_name='id_interno',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='peso_bruto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='peso_neto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='promedio',
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_items', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='dia_embarque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='embarque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('DEBE', 'Pendiente (Crédito)'), ('PAGADA', 'Pagada Totalmente'), ('PARCIAL', 'Abonada / Parcial'), ('ANULADA', 'Anulada')], default='DEBE', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.CharField(max_length=50, unique=True, verbose_name='N° Factura'),
        ),
    ]
