# Generated by Django 5.2.5 on 2026-03-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0002_embarque_bolsas_mantequilla_and_more'),
        ('ventas', '0002_rename_numero_venta_id_interno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(default='FV', help_text='Ej: FV, FAC, INV', max_length=10, verbose_name='Prefijo de factura')),
                ('numero_inicio', models.PositiveIntegerField(default=1, help_text='El consecutivo empezará desde este número.', verbose_name='Número inicial')),
            ],
            options={
                'verbose_name': 'Configuración de Facturas',
                'verbose_name_plural': 'Configuración de Facturas',
            },
        ),
        migrations.AlterField(
            model_name='venta',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='embarques.embarque', verbose_name='Embarque / Ruta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.CharField(blank=True, help_text='Se genera automáticamente. No editar.', max_length=50, unique=True, verbose_name='N° Factura'),
        ),
    ]
