# Generated by Django 5.2.5 on 2026-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('embarques', '0002_embarque_bolsas_mantequilla_and_more'),
        ('ventas', '0003_configuracionfactura_alter_venta_embarque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha', '-id_interno'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_vent_fecha_8683f5_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_vent_estado_b0d674_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['factura'], name='ventas_vent_factura_e27aff_idx'),
        ),
    ]
