# Generated by Django 5.2.5 on 2026-03-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0003_ruta_tipoembalaje_transportador_vehiculo_and_more'),
        ('ventas', '0004_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='dia_embarque',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_devuelta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad que regresó físicamente al camión', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='canastillas_devueltas',
            field=models.PositiveIntegerField(default=0, help_text='Canastillas que regresaron (devolución/cambio)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='canastillas_entregadas',
            field=models.PositiveIntegerField(default=0, help_text='Canastillas físicamente entregadas'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad facturada / entregada', max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='embarques.embarque', verbose_name='Embarque / Ruta'),
        ),
    ]
