# Generated by Django 5.2.5 on 2026-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_venta_conductor_remove_venta_dia_embarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Venta confirmada por el cargador/controlador'),
        ),
    ]
