# Generated by Django 5.2.5 on 2026-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='conductor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
