# Generated by Django 5.2.5 on 2026-03-02 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0008_remove_embarque_actualizado_en_and_more'),
        ('ventas', '0007_venta_conductor_venta_placa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='canastillas_devueltas',
            new_name='total_embalajes_devueltos',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='canastillas_entregadas',
            new_name='total_embalajes_entregados',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad_devuelta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_devuelta_facturada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kilos o Unidades descontadas financieramente', max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_facturada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad monetizada (Kilos o Unidades exactas)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='unidades_devueltas',
            field=models.PositiveIntegerField(default=0, help_text='Unidades físicas que regresaron'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='unidades_entregadas',
            field=models.PositiveIntegerField(default=1, help_text='Unidades físicas (bloques, paquetes) entregadas'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='embarque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='embarques.embarque', verbose_name='Embarque / Ruta'),
            preserve_default=False,
        ),
    ]
