# Generated by Django 5.2.5 on 2026-03-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_rename_canastillas_devueltas_venta_total_embalajes_devueltos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='embalajes_entregados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Canastillas calculadas para este item (Ej: 16 unds = 1 canastilla)', max_digits=8),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_embalajes_automatico',
            field=models.BooleanField(default=True, help_text='Si está activo, el sistema estima las canastillas según la configuración del producto'),
        ),
    ]
