# Generated by Django 5.2.5 on 2026-03-03 05:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_historicalcliente'),
        ('embarques', '0009_capacidadembalaje_metodo_calculo_and_more'),
        ('productos', '0005_alter_producto_control_inventario_and_more'),
        ('ventas', '0009_detalleventa_embalajes_entregados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDetalleVenta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última Modificación')),
                ('unidades_entregadas', models.PositiveIntegerField(default=1, help_text='Unidades físicas (bloques, paquetes) entregadas')),
                ('unidades_devueltas', models.PositiveIntegerField(default=0, help_text='Unidades físicas que regresaron')),
                ('cantidad_facturada', models.DecimalField(decimal_places=2, help_text='Cantidad monetizada (Kilos o Unidades exactas)', max_digits=12)),
                ('cantidad_devuelta_facturada', models.DecimalField(decimal_places=2, default=0, help_text='Kilos o Unidades descontadas financieramente', max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('embalajes_entregados', models.DecimalField(decimal_places=2, default=0, help_text='Canastillas calculadas para este item (Ej: 16 unds = 1 canastilla)', max_digits=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.producto')),
                ('usuario_registro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'historical detalle venta',
                'verbose_name_plural': 'historical detalle ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVenta',
            fields=[
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última Modificación')),
                ('id_interno', models.IntegerField(blank=True, db_index=True)),
                ('factura', models.CharField(blank=True, db_index=True, help_text='Se genera automáticamente. No editar.', max_length=50, verbose_name='N° Factura')),
                ('fecha', models.DateField()),
                ('conductor', models.CharField(blank=True, max_length=150, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('total_embalajes_entregados', models.PositiveIntegerField(default=0, help_text='Canastillas físicamente entregadas')),
                ('total_embalajes_devueltos', models.PositiveIntegerField(default=0, help_text='Canastillas que regresaron (devolución/cambio)')),
                ('flete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_con_flete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_embalajes_automatico', models.BooleanField(default=True, help_text='Si está activo, el sistema estima las canastillas según la configuración del producto')),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confirmado', models.BooleanField(default=False, help_text='Venta confirmada por el cargador/controlador')),
                ('estado', models.CharField(choices=[('DEBE', 'Pendiente (Crédito)'), ('PAGADA', 'Pagada Totalmente'), ('PARCIAL', 'Abonada / Parcial'), ('ANULADA', 'Anulada')], default='DEBE', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('embarque', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='embarques.embarque', verbose_name='Embarque / Ruta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Venta',
                'verbose_name_plural': 'historical Ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
