# Generated by Django 5.2.5 on 2026-03-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0010_alter_embarque_estado_embarqueitem_novedadembarque_and_more'),
        ('ventas', '0010_historicaldetalleventa_historicalventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_unidades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='embarque_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='embarques.embarqueitem'),
        ),
        migrations.AddField(
            model_name='historicaldetalleventa',
            name='cantidad_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetalleventa',
            name='cantidad_unidades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetalleventa',
            name='embarque_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='embarques.embarqueitem'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad_devuelta_facturada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad_facturada',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='embalajes_entregados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Canastillas calculadas para este item', max_digits=8),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='unidades_devueltas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='unidades_entregadas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicaldetalleventa',
            name='cantidad_devuelta_facturada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldetalleventa',
            name='cantidad_facturada',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldetalleventa',
            name='embalajes_entregados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Canastillas calculadas para este item', max_digits=8),
        ),
        migrations.AlterField(
            model_name='historicaldetalleventa',
            name='unidades_devueltas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicaldetalleventa',
            name='unidades_entregadas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
