# Generated by Django 5.2.5 on 2026-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_detalleventa_cantidad_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetalleventa',
            name='cantidad_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
