# Generated by Django 5.2.5 on 2026-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_detalleventa_cantidad_litros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_tajado_unidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo adicional por unidad tajada', max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tajado',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Tajado?'),
        ),
        migrations.AddField(
            model_name='historicaldetalleventa',
            name='precio_tajado_unidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo adicional por unidad tajada', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldetalleventa',
            name='tajado',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Tajado?'),
        ),
        migrations.AddField(
            model_name='historicalventa',
            name='flete_cobrado_al_cliente',
            field=models.BooleanField(default=False, help_text='SI: se suma al total. NO: se resta del total (descuento logístico).', verbose_name='Flete cobrado al cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='flete_cobrado_al_cliente',
            field=models.BooleanField(default=False, help_text='SI: se suma al total. NO: se resta del total (descuento logístico).', verbose_name='Flete cobrado al cliente'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='total_con_flete',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_con_flete',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
