# Generated by Django 5.2.5 on 2025-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('LB', 'Libra'), ('1/2LB', 'Media Libra'), ('CAN', 'Canastilla'), ('LTS', 'Litros')], default='UND', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('control_inventario', models.BooleanField(default=False, help_text='Si está activo, descuenta stock al vender')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
