# Generated by Django 5.2.5 on 2025-09-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (opcional)', null=True, upload_to='productos/'),
        ),
    ]
