# Generated by Django 5.2.5 on 2026-03-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_promedio_unidad',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Peso base de 1 unidad comercial para conversiones aprox.', max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_control',
            field=models.CharField(choices=[('EXACTO', 'Control por Unidad Exacta (Ej: Doble Crema)'), ('PESO', 'Control por Peso con Tolerancia (Ej: Cuajada)')], default='EXACTO', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='tolerancia_merma',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Tolerancia de merma. Ej: 0.05 para 5%', max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
