# Generated by Django 5.2.5 on 2026-03-03 05:22

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='control_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_promedio_unidad',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_control',
            field=models.CharField(choices=[('EXACTO', 'Control por Unidad Exacta'), ('PESO', 'Control por Peso con Tolerancia')], default='EXACTO', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tolerancia_merma',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última Modificación')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, help_text='Imagen del producto', max_length=100, null=True)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('LB', 'Libra'), ('1/2LB', 'Media Libra'), ('CAN', 'Canastilla'), ('LTS', 'Litros')], default='UND', max_length=10)),
                ('tipo_control', models.CharField(choices=[('EXACTO', 'Control por Unidad Exacta'), ('PESO', 'Control por Peso con Tolerancia')], default='EXACTO', max_length=15)),
                ('tolerancia_merma', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('peso_promedio_unidad', models.DecimalField(decimal_places=3, default=1.0, max_digits=8)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('control_inventario', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producto',
                'verbose_name_plural': 'historical productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
