# Generated by Django 5.2.5 on 2026-03-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0010_alter_embarque_estado_embarqueitem_novedadembarque_and_more'),
        ('productos', '0005_alter_producto_control_inventario_and_more'),
        ('ventas', '0011_detalleventa_cantidad_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='unidad_medida',
            field=models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('LB', 'Libra'), ('1/2LB', 'Media Libra'), ('CAN', 'Canastilla'), ('LTS', 'Litros')], db_column='unidad_medida', default='UND', max_length=10),
        ),
        migrations.RenameField(
            model_name='historicalproducto',
            old_name='unidad_medida',
            new_name='unidad_medida_old',
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('LB', 'Libra'), ('1/2LB', 'Media Libra'), ('CAN', 'Canastilla'), ('LTS', 'Litros')], db_column='unidad_medida', default='UND', max_length=10),
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='unidad_medida',
            new_name='unidad_medida_old',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='tipo_control',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_control',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='controla_peso_variable',
            field=models.BooleanField(default=False, help_text='Si es True, se debe registrar peso (kg) y unidades físicas (ej: Cuajada).'),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='tipo_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo')], default='unidad', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='controla_peso_variable',
            field=models.BooleanField(default=False, help_text='Si es True, se debe registrar peso (kg) y unidades físicas (ej: Cuajada).'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo')], default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='control_inventario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='control_inventario',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salida_embarque', 'Salida a tránsito'), ('venta', 'Venta'), ('devolucion', 'Devolución'), ('reposicion', 'Reposición'), ('ajuste_merma', 'Merma por desuerado'), ('ajuste_diferencia', 'Ajuste diferencia')], max_length=20)),
                ('cantidad_unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('embarque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='embarques.embarque')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
