# Generated by Django 5.2.5 on 2026-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_historicalproducto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cantidad_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='tipo_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('litro', 'Litro')], default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('litro', 'Litro')], default='unidad', max_length=10),
        ),
    ]
