# Generated by Django 5.2.5 on 2026-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_movimientoinventario_cantidad_litros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra / Entrada Almacén'), ('salida_embarque', 'Salida a tránsito'), ('venta', 'Venta'), ('devolucion', 'Devolución'), ('reposicion', 'Reposición'), ('ajuste_merma', 'Merma por desuerado'), ('ajuste_diferencia', 'Ajuste diferencia'), ('ajuste_positivo', 'Ajuste de inventario (+)'), ('retorno_almacen', 'Retorno a almacén (de camión)')], max_length=20),
        ),
    ]
