# Generated by Django 5.2.5 on 2025-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('numero_unico', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('forma_pago', models.CharField(choices=[('contado', 'Contado'), ('credito_15', 'Crédito a 15 días'), ('credito_30', 'Crédito a 30 días'), ('credito_60', 'Crédito a 60 días'), ('otro', 'Otro')], max_length=20)),
                ('dias_credito', models.PositiveIntegerField(blank=True, help_text="Si selecciona 'Otro', especifique los días de crédito", null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
