# Generated by Django 5.2.5 on 2026-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_identificacion'], name='clientes_cl_numero__e3542c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre', 'apellido'], name='clientes_cl_nombre_676dbe_idx'),
        ),
    ]
