# Generated by Django 5.2.5 on 2025-11-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_tipo_proveedor_and_more'),
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoleccion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='recoleccion.ruta'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
