# Generated by Django 5.2.5 on 2025-09-23 22:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('conductor', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de costo',
                'verbose_name_plural': 'Tipos de costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Notas adicionales (opcional). No usar para tipificar el costo.', max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unidad', models.CharField(choices=[('UND', 'Unidades'), ('KG', 'Kilogramos'), ('CAN', 'Canastillas'), ('LTS', 'Litros'), ('COP', 'Pesos (COP)')], default='COP', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='embarques/%Y%m%d/costos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='embarques.embarque')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='embarques.tipocosto')),
            ],
            options={
                'verbose_name': 'Costo de embarque',
                'verbose_name_plural': 'Costos de embarque',
                'ordering': ['-fecha', 'tipo__nombre'],
            },
        ),
    ]
