# Generated by Django 5.2.5 on 2025-12-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='bolsas_mantequilla',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embarque',
            name='canastillas_crema',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embarque',
            name='canastillas_cuajada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embarque',
            name='canastillas_queso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embarque',
            name='canastillas_tajado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
