# Generated by Django 5.2.5 on 2026-03-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0002_embarque_bolsas_mantequilla_and_more'),
        ('productos', '0003_alter_producto_precio_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudades_itinerario', models.TextField(help_text='Lista de ciudades separadas por coma')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='TipoEmbalaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('peso_vacio_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo de Embalaje',
                'verbose_name_plural': 'Tipos de Embalaje',
            },
        ),
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tarifa_base_viaje', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transportador',
                'verbose_name_plural': 'Transportadores',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_carga_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.RenameField(
            model_name='embarque',
            old_name='bolsas_mantequilla',
            new_name='canastillas_enviadas',
        ),
        migrations.RenameField(
            model_name='embarque',
            old_name='canastillas_crema',
            new_name='canastillas_regresadas',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_cuajada',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_queso',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_tajado',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='placa',
        ),
        migrations.AddField(
            model_name='embarque',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('CARGANDO', 'En Cargue'), ('EN_RUTA', 'En Ruta'), ('FINALIZADO', 'Finalizado / Liquidado'), ('ANULADO', 'Anulado')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='embarque',
            name='gastos_operativos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='embarque',
            name='ingresos_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='embarque',
            name='pago_transportador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='embarque',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='embarque',
            name='utilidad_neta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='GastoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMBUSTIBLE', 'Combustible'), ('PEAJE', 'Peajes'), ('MANTENIMIENTO', 'Mantenimiento en ruta'), ('ALIMENTACION', 'Viáticos / Alimentación'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='embarques/gastos/')),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='embarques.embarque')),
            ],
        ),
        migrations.AddField(
            model_name='embarque',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='embarques.ruta'),
        ),
        migrations.CreateModel(
            name='EmbarqueCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.DecimalField(decimal_places=2, max_digits=12)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga_inicial', to='embarques.embarque')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('tipo_embalaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='embarques.tipoembalaje')),
            ],
        ),
        migrations.CreateModel(
            name='CapacidadEmbalaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_por_paquete', models.PositiveIntegerField(help_text='Ej: 16 unidades de queso por canastilla')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades_embalaje', to='productos.producto')),
                ('tipo_embalaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embarques.tipoembalaje')),
            ],
            options={
                'verbose_name': 'Capacidad de Embalaje',
                'verbose_name_plural': 'Capacidades de Embalaje',
                'unique_together': {('producto', 'tipo_embalaje')},
            },
        ),
        migrations.CreateModel(
            name='TarifaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('precio_por_embalaje', models.DecimalField(decimal_places=2, help_text='Pago al transportador por cada canastilla entregada', max_digits=10)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embarques.ruta')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='embarques.transportador')),
            ],
            options={
                'unique_together': {('transportador', 'ruta', 'ciudad')},
            },
        ),
        migrations.AddField(
            model_name='embarque',
            name='transportador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='embarques.transportador'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='embarques.vehiculo'),
        ),
        migrations.DeleteModel(
            name='CostoEmbarque',
        ),
        migrations.DeleteModel(
            name='TipoCosto',
        ),
    ]
