# Generated by Django 5.2.5 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0003_ruta_tipoembalaje_transportador_vehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_regresadas',
        ),
        migrations.AddField(
            model_name='embarque',
            name='canastillas_devueltas',
            field=models.PositiveIntegerField(default=0, help_text='Total canastillas regresadas físicamente'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='canastillas_entregadas',
            field=models.PositiveIntegerField(default=0, help_text='Total canastillas entregadas según facturas'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso total de la carga (productos + embalaje)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='canastillas_enviadas',
            field=models.PositiveIntegerField(default=0, help_text='Total canastillas cargadas inicialmente'),
        ),
    ]
