# Generated by Django 5.2.5 on 2026-03-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0004_remove_embarque_canastillas_regresadas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarifatransporte',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tarifatransporte',
            name='tipo_embalaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='embarques.tipoembalaje'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifatransporte',
            unique_together={('transportador', 'ruta', 'ciudad', 'tipo_embalaje')},
        ),
    ]
