# Generated by Django 5.2.5 on 2026-03-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0005_alter_tarifatransporte_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='vehiculo_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='embarques.vehiculo'),
        ),
    ]
