# Generated by Django 5.2.5 on 2026-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0006_ruta_vehiculo_predeterminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='conductor',
            field=models.CharField(blank=True, help_text='Nombre del conductor asignado', max_length=150, null=True),
        ),
    ]
