# Generated by Django 5.2.5 on 2026-03-02 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0007_embarque_conductor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_devueltas',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_entregadas',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='canastillas_enviadas',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='usuario_registra',
        ),
        migrations.AddField(
            model_name='embarque',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embarque',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='total_embalajes_devueltos',
            field=models.PositiveIntegerField(default=0, help_text='Total embalajes regresados físicamente'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='total_embalajes_entregados',
            field=models.PositiveIntegerField(default=0, help_text='Total embalajes entregados según facturas'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='total_embalajes_enviados',
            field=models.PositiveIntegerField(default=0, help_text='Total embalajes cargados inicialmente'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to=settings.AUTH_USER_MODEL),
        ),
    ]
