# Generated by Django 5.2.5 on 2026-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0008_remove_embarque_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadembalaje',
            name='metodo_calculo',
            field=models.CharField(choices=[('UNIDADES', 'Contar unidades físicas (bloques, bolsas)'), ('CANTIDAD', 'Contar cantidad facturada (Kg, Litros)')], default='UNIDADES', help_text='Decide si el cálculo se hace por unidades físicas o por cantidad comercial', max_length=15),
        ),
        migrations.AlterField(
            model_name='capacidadembalaje',
            name='unidades_por_paquete',
            field=models.DecimalField(decimal_places=4, help_text='Ej: 16 unidades o 38.5 kg por canastilla', max_digits=12),
        ),
    ]
