# Generated by Django 5.2.5 on 2026-03-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0009_capacidadembalaje_metodo_calculo_and_more'),
        ('productos', '0005_alter_producto_control_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarque',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('transito', 'En tránsito'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='EmbarqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_disponible_unidades', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_disponible_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='embarques.embarque')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('tipo_embalaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='embarques.tipoembalaje')),
            ],
        ),
        migrations.CreateModel(
            name='NovedadEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('devolucion', 'Devolución'), ('reposicion', 'Reposición'), ('ajuste_merma', 'Merma por desuerado'), ('ajuste_diferencia', 'Ajuste diferencia'), ('daño', 'Producto Dañado')], max_length=20)),
                ('cantidad_unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='embarques.embarque')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Novedad de Embarque',
                'verbose_name_plural': 'Novedades de Embarque',
            },
        ),
        migrations.DeleteModel(
            name='EmbarqueCarga',
        ),
    ]
