# Generated by Django 5.2.5 on 2026-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0010_alter_embarque_estado_embarqueitem_novedadembarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarqueitem',
            name='cantidad_disponible_litros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='embarqueitem',
            name='cantidad_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
