# Generated by Django 5.2.5 on 2026-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0011_embarqueitem_cantidad_disponible_litros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadembarque',
            name='cantidad_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
