# Generated by Django 5.2.5 on 2025-11-08 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proveedor',
                'verbose_name_plural': 'Tipos de Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='proveedores.tipoproveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
