# Generated by Django 5.2.5 on 2025-11-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_proveedor',
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='correo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='identificacion',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='ruts/'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoProveedor',
        ),
    ]
