# Generated by Django 5.2.5 on 2025-11-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_tipo_proveedor_and_more'),
        ('recoleccion', '0002_alter_recoleccion_proveedor_recoleccion_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recoleccion.ruta'),
        ),
    ]
